import {assert, check} from '@augment-vir/assert';
import {
    combineErrorMessages,
    ensureError,
    ensureErrorClass,
    extractErrorMessage,
    getEnumValues,
    getObjectTypedKeys,
    HttpMethod,
    HttpStatus,
    randomString,
    type SelectFrom,
} from '@augment-vir/common';
import compressPlugin from '@fastify/compress';
import fastifyWs from '@fastify/websocket';
import {type BaseSearchParams, type MinimalService} from '@rest-vir/define-service';
import {
    RestVirHandlerError,
    ServiceImplementation,
    type GenericServiceImplementation,
    type RunningServerInfo,
} from '@rest-vir/implement-service';
import {type FastifyInstance} from 'fastify';
import {buildUrl, parseUrl} from 'url-vir';
import {handleHandlerOutput, type HandleRouteOptions} from '../handle-request/endpoint-handler.js';
import {handleRoute} from '../handle-request/handle-route.js';
import {preHandler} from '../handle-request/pre-handler.js';
import {runPostHook} from '../handle-request/run-post-hook.js';

/**
 * Context attached to each fastify request object.
 *
 * @category Internal
 * @category Package : @rest-vir/run-service
 * @package [`@rest-vir/run-service`](https://www.npmjs.com/package/@rest-vir/run-service)
 */
export type RestVirRequestContext = {
    context: unknown;
    requestData: unknown;
    protocols: string[];
    searchParams: BaseSearchParams;
};

declare module 'fastify' {
    interface FastifyRequest {
        restVirContext:
            | {
                  /**
                   * {@link attachService} can be called multiple times. Each time it is called, a
                   * new `AttachId` is generated and contexts generated by that attachment are
                   * stored in the request under that id.
                   */
                  [AttachId in string]: Partial<RestVirRequestContext>;
              }
            | undefined;
    }
}

const endpointFastifyMethods = getEnumValues(HttpMethod).filter((value) => {
    return (
        /** Fastify doesn't support the CONNECT method. */
        value !== HttpMethod.Connect &&
        /** We use the GET method in a separate handler so it can handle WebSocket requests as well. */
        value !== HttpMethod.Get
    );
});

/**
 * Attach all handlers for a {@link ServiceImplementation} to any existing Fastify server.
 *
 * @category Run Service
 * @category Package : @rest-vir/run-service
 * @example
 *
 * ```ts
 * import fastify from 'fastify';
 *
 * const server = fastify();
 *
 * attachService(service, myServiceImplementation);
 *
 * await server.listen({port: 3000});
 * ```
 *
 * @package [`@rest-vir/run-service`](https://www.npmjs.com/package/@rest-vir/run-service)
 */
export async function attachService(
    server: Readonly<FastifyInstance>,
    service: Readonly<
        SelectFrom<
            GenericServiceImplementation,
            {
                webSockets: true;
                endpoints: true;
                serviceName: true;
                createContext: true;
                serviceOrigin: true;
                requiredClientOrigin: true;
                logger: true;
                postHook: true;
            }
        >
    >,
    options: Readonly<HandleRouteOptions> = {},
): Promise<void> {
    try {
        const attachId = randomString(32);

        if (!server.hasRequestDecorator('restVirContext')) {
            server.decorateRequest('restVirContext');
        }

        await server.register(compressPlugin, {
            encodings: [
                'br',
                'gzip',
                'deflate',
            ],
        });

        if (!server.hasRequestDecorator('ws')) {
            await server.register(fastifyWs, {
                /* node:coverage ignore next 14: edge case handling */
                errorHandler(error, webSocket, request) {
                    service.logger.error(
                        new RestVirHandlerError(
                            {
                                isEndpoint: false,
                                isWebSocket: true,
                                path: request.originalUrl,
                                service,
                            },
                            extractErrorMessage(error),
                        ),
                    );
                    webSocket.terminate();
                },
            });
        }

        const postHook = service.postHook;

        server.addHook('preValidation', async (request, response) => {
            try {
                const preHandlerResult = await preHandler({
                    request,
                    response,
                    service,
                    server: extractRunningServerInfo(service, server),
                    attachId,
                });

                if (preHandlerResult?.statusCode && postHook) {
                    const postHookResult = await runPostHook({
                        attachId,
                        originalBody: preHandlerResult.body,
                        originalStatus: preHandlerResult.statusCode,
                        postHook,
                        request,
                        response,
                        server: extractRunningServerInfo(service, server),
                        service,
                    });

                    if (postHookResult) {
                        return handleHandlerOutput(postHookResult, response);
                    }
                }

                return handleHandlerOutput(preHandlerResult, response);
            } catch (error) {
                service.logger.error(
                    ensureErrorClass(
                        error,
                        RestVirHandlerError,
                        {
                            isEndpoint: undefined,
                            isWebSocket: undefined,
                            path: request.originalUrl,
                            service,
                        },
                        combineErrorMessages('Unexpected error', extractErrorMessage(error)),
                    ),
                );
                if (options.throwErrorsForExternalHandling) {
                    throw error;
                    /* node:coverage ignore next 5 */
                } else if (response.sent) {
                    assert.never(
                        "Error encountered but response was already sent so there's nothing we can do about it.",
                    );
                } else {
                    response.statusCode = HttpStatus.InternalServerError;
                    return response.send();
                }
            }
        });

        const allPaths = new Set([
            ...getObjectTypedKeys(service.webSockets),
            ...getObjectTypedKeys(service.endpoints),
        ]);

        allPaths.forEach((path) => {
            const webSocketDefinition = service.webSockets[path];
            const endpoint = service.endpoints[path];

            if (endpoint && webSocketDefinition) {
                server.route({
                    method: endpointFastifyMethods,
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpoint,
                            attachId,
                            server: extractRunningServerInfo(service, server),
                            options,
                            postHook,
                            service,
                        });
                    },
                });
                server.route({
                    method: HttpMethod.Get,
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpoint,
                            attachId,
                            server: extractRunningServerInfo(service, server),
                            options,
                            postHook,
                            service,
                        });
                    },
                    wsHandler(webSocket, request) {
                        return handleRoute({
                            webSocket,
                            request,
                            response: undefined,
                            route: webSocketDefinition,
                            attachId,
                            server: extractRunningServerInfo(service, server),
                            options,
                            postHook,
                            service,
                        });
                    },
                });
            } else if (endpoint) {
                server.route({
                    method: [
                        ...endpointFastifyMethods,
                        HttpMethod.Get,
                    ],
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpoint,
                            attachId,
                            server: extractRunningServerInfo(service, server),
                            options,
                            postHook,
                            service,
                        });
                    },
                });
            } else if (webSocketDefinition) {
                server.route({
                    method: HttpMethod.Get,
                    url: path,
                    handler(request, response) {
                        return response.status(HttpStatus.NotFound).send();
                    },
                    wsHandler(webSocket, request) {
                        return handleRoute({
                            webSocket,
                            request,
                            response: undefined,
                            route: webSocketDefinition,
                            attachId,
                            server: extractRunningServerInfo(service, server),
                            options,
                            postHook,
                            service,
                        });
                    },
                });
            }
        });

        /* node:coverage ignore next 4: this is just here to cover edge cases. */
    } catch (error) {
        service.logger.error(ensureError(error));
        throw error;
    }
}

/**
 * Merge the running Fastify server's port with the given service's origin port (if it has a port).
 *
 * @category Internal
 */
export function extractRunningServerInfo(
    service: Readonly<Pick<MinimalService, 'serviceOrigin'>>,
    fastify: Readonly<
        SelectFrom<
            FastifyInstance,
            {
                server: {
                    address: true;
                };
            }
        >
    >,
): RunningServerInfo {
    const address = fastify.server.address();

    const {port: originalPort} = parseUrl(service.serviceOrigin);

    if (!originalPort || check.isString(address) || !address) {
        return {
            serviceOrigin: service.serviceOrigin,
        };
    } else {
        const {origin} = buildUrl(service.serviceOrigin, {
            port: address.port,
        });

        return {
            serviceOrigin: origin,
        };
    }
}
