import {assert, check} from '@augment-vir/assert';
import {
    combineErrorMessages,
    ensureError,
    ensureErrorClass,
    extractErrorMessage,
    getEnumValues,
    getObjectTypedKeys,
    HttpMethod,
    HttpStatus,
    randomString,
    type SelectFrom,
} from '@augment-vir/common';
import compressPlugin from '@fastify/compress';
import fastifyWs from '@fastify/websocket';
import {type BaseSearchParams} from '@rest-vir/api';
import {type FastifyInstance} from 'fastify';
import {buildUrl, parseUrl} from 'url-vir';
import {type ApiImplementation} from '../../implementation/implement-api.js';
import {type RunningServerInfo} from '../../implementation/raw-route-data.js';
import {createServerLogger} from '../../implementation/server-logger.js';
import {handleHandlerOutput, type HandleRouteOptions} from '../handle-request/endpoint-handler.js';
import {handleRoute} from '../handle-request/handle-route.js';
import {preHandler} from '../handle-request/pre-handler.js';
import {runPostRouteHook} from '../handle-request/run-post-route-hook.js';
import {RestVirHandlerError} from '../util/handler.error.js';

/**
 * Context attached to each fastify request object.
 *
 * @category Internal
 * @category Package : @rest-vir/run-service
 * @package [`@rest-vir/run-service`](https://www.npmjs.com/package/@rest-vir/run-service)
 */
export type RestVirRequestContext = {
    context: unknown;
    requestData: unknown;
    protocols: string[];
    searchParams: BaseSearchParams;
};

declare module 'fastify' {
    interface FastifyRequest {
        restVirContext:
            | {
                  /**
                   * {@link attachService} can be called multiple times. Each time it is called, a
                   * new `AttachId` is generated and contexts generated by that attachment are
                   * stored in the request under that id.
                   */
                  [AttachId in string]: Partial<RestVirRequestContext>;
              }
            | undefined;
    }
}

const endpointFastifyMethods = getEnumValues(HttpMethod).filter((value) => {
    return (
        /** Fastify doesn't support the CONNECT method. */
        value !== HttpMethod.Connect &&
        /** We use the GET method in a separate handler so it can handle WebSocket requests as well. */
        value !== HttpMethod.Get
    );
});

export type ApiServerOptions = {
    /**
     * The origin at which the api is hosted on. Fetch requests and WebSocket connections should be
     * sent to this origin to connect with this server. The internal server alone will not know what
     * this is (since it's going to just be listening on some localhost port), so you must provide
     * this so that the endpoint handlers know what the current origin is.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/API/Location for help on which part of the URL is the origin (if necessary).
     */
    serverOrigin: string;
};

/**
 * Attach all handlers for a {@link ServiceImplementation} to any existing Fastify server.
 *
 * @category Run Service
 * @category Package : @rest-vir/run-service
 * @example
 *
 * ```ts
 * import fastify from 'fastify';
 *
 * const server = fastify();
 *
 * attachService(service, myServiceImplementation);
 *
 * await server.listen({port: 3000});
 * ```
 *
 * @package [`@rest-vir/run-service`](https://www.npmjs.com/package/@rest-vir/run-service)
 */
export async function attachApi(
    server: Readonly<FastifyInstance>,
    api: Readonly<ApiImplementation>,
    options: Readonly<ApiServerOptions & HandleRouteOptions>,
): Promise<void> {
    const serverLogger = createServerLogger(api.implementation.serverLogger);

    try {
        const attachId = randomString(32);

        if (!server.hasRequestDecorator('restVirContext')) {
            server.decorateRequest('restVirContext');
        }

        await server.register(compressPlugin, {
            encodings: [
                'br',
                'gzip',
                'deflate',
            ],
        });

        if (!server.hasRequestDecorator('ws')) {
            await server.register(fastifyWs, {
                /* node:coverage ignore next 14: edge case handling */
                errorHandler(error, webSocket, request) {
                    serverLogger.error(
                        new RestVirHandlerError(
                            {
                                isEndpoint: false,
                                isWebSocket: true,
                                path: request.originalUrl,
                                apiName: api.definition.apiName,
                            },
                            extractErrorMessage(error),
                            HttpStatus.InternalServerError,
                        ),
                    );
                    webSocket.terminate();
                },
            });
        }

        const postHook = api.implementation.postRouteHook;

        server.addHook('preValidation', async (request, response) => {
            try {
                const preHandlerResult = await preHandler({
                    request,
                    response,
                    api,
                    server: extractRunningServerInfo(options, server),
                    attachId,
                    serverLogger,
                });

                if (preHandlerResult?.statusCode && postHook) {
                    const postHookResult = await runPostRouteHook({
                        attachId,
                        originalBody: preHandlerResult.body,
                        originalStatus: preHandlerResult.statusCode,
                        postHook,
                        request,
                        response,
                        server: extractRunningServerInfo(options, server),
                        api,
                        serverLogger,
                    });

                    if (postHookResult) {
                        return handleHandlerOutput(postHookResult, response);
                    }
                }

                return handleHandlerOutput(preHandlerResult, response);
            } catch (error) {
                serverLogger.error(
                    ensureErrorClass(
                        error,
                        RestVirHandlerError,
                        {
                            isEndpoint: undefined,
                            isWebSocket: undefined,
                            path: request.originalUrl,
                            apiName: api.definition.apiName,
                        },
                        combineErrorMessages('Unexpected error', extractErrorMessage(error)),
                        HttpStatus.InternalServerError,
                    ),
                );
                if (options.throwErrorsForExternalHandling) {
                    throw error;
                    /* node:coverage ignore next 5 */
                } else if (response.sent) {
                    assert.never(
                        "Error encountered but response was already sent so there's nothing we can do about it.",
                    );
                } else {
                    response.statusCode = HttpStatus.InternalServerError;
                    return response.send();
                }
            }
        });

        const allPaths = new Set([
            ...getObjectTypedKeys(api.implementation.webSockets),
            ...getObjectTypedKeys(api.implementation.endpoints),
        ]);

        allPaths.forEach((path) => {
            const webSocketImplementation = api.implementation.webSockets[path];
            const endpointImplementation = api.implementation.endpoints[path];

            if (endpointImplementation && webSocketImplementation) {
                server.route({
                    method: endpointFastifyMethods,
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpointImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                });
                server.route({
                    method: HttpMethod.Get,
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpointImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                    wsHandler(webSocket, request) {
                        return handleRoute({
                            webSocket,
                            request,
                            response: undefined,
                            route: webSocketImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                });
            } else if (endpointImplementation) {
                server.route({
                    method: [
                        ...endpointFastifyMethods,
                        HttpMethod.Get,
                    ],
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpointImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                });
            } else if (webSocketImplementation) {
                server.route({
                    method: HttpMethod.Get,
                    url: path,
                    handler(request, response) {
                        return response.status(HttpStatus.NotFound).send();
                    },
                    wsHandler(webSocket, request) {
                        return handleRoute({
                            webSocket,
                            request,
                            response: undefined,
                            route: webSocketImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                });
            }
        });

        /* node:coverage ignore next 4: this is just here to cover edge cases. */
    } catch (error) {
        serverLogger.error(ensureError(error));
        throw error;
    }
}

/**
 * Merge the running Fastify server's port with the given service's origin port (if it has a port).
 *
 * @category Internal
 */
export function extractRunningServerInfo(
    serverOptions: Readonly<ApiServerOptions>,
    fastify: Readonly<
        SelectFrom<
            FastifyInstance,
            {
                server: {
                    address: true;
                };
            }
        >
    >,
): RunningServerInfo {
    const address = fastify.server.address();

    const {port: originalPort} = parseUrl(serverOptions.serverOrigin);

    if (!originalPort || check.isString(address) || !address) {
        return {
            serviceOrigin: serverOptions.serverOrigin,
        };
    } else {
        const {origin} = buildUrl(serverOptions.serverOrigin, {
            port: address.port,
        });

        return {
            serviceOrigin: origin,
        };
    }
}
