import {check} from '@augment-vir/assert';
import {
    combineErrorMessages,
    ensureError,
    ensureErrorClass,
    extractErrorMessage,
    getEnumValues,
    getObjectTypedKeys,
    HttpMethod,
    HttpStatus,
    randomString,
    type SelectFrom,
} from '@augment-vir/common';
import compressPlugin from '@fastify/compress';
import multipartPlugin from '@fastify/multipart';
import fastifyWs from '@fastify/websocket';
import {isFormDataShape, type BaseSearchParams} from '@rest-vir/api';
import {type FastifyInstance} from 'fastify';
import {buildUrl, parseUrl} from 'url-vir';
import {type ApiImplementation} from '../../implementation/implement-api.js';
import {type RunningServerInfo} from '../../implementation/raw-route-data.js';
import {RejectRequestError} from '../../implementation/reject-request.error.js';
import {createServerLogger} from '../../implementation/server-logger.js';
import {handleHandlerOutput, type HandleRouteOptions} from '../handle-request/endpoint-handler.js';
import {handleRoute} from '../handle-request/handle-route.js';
import {preHandler} from '../handle-request/pre-handler.js';
import {runPostRouteHook} from '../handle-request/run-post-route-hook.js';
import {RestVirHandlerError} from '../util/handler.error.js';

/**
 * Context attached to each fastify request object.
 *
 * @category Internal
 * @category Package : @rest-vir/host
 * @package [`@rest-vir/host`](https://www.npmjs.com/package/@rest-vir/host)
 */
export type RestVirRequestContext = {
    context: unknown;
    requestData: unknown;
    protocols: string[];
    searchParams: BaseSearchParams;
};

declare module 'fastify' {
    interface FastifyRequest {
        restVirContext:
            | {
                  /**
                   * {@link attachApi} can be called multiple times. Each time it is called, a new
                   * `AttachId` is generated and contexts generated by that attachment are stored in
                   * the request under that id.
                   */
                  [AttachId in string]: Partial<RestVirRequestContext>;
              }
            | undefined;
    }
}

const endpointFastifyMethods = getEnumValues(HttpMethod).filter((value) => {
    return (
        /** Fastify doesn't support the CONNECT method. */
        value !== HttpMethod.Connect &&
        /** We use the GET method in a separate handler so it can handle WebSocket requests as well. */
        value !== HttpMethod.Get
    );
});

export type ApiServerOptions = {
    /**
     * The origin at which the api is hosted on. Fetch requests and WebSocket connections should be
     * sent to this origin to connect with this server. The internal server alone will not know what
     * this is (since it's going to be listening on some localhost port), so you must provide this
     * so that the endpoint handlers know what the current origin is.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/API/Location for help on which part of the URL is the origin (if necessary).
     */
    externalOrigin: string;
    /**
     * Maximum size, in bytes, of an inbound WebSocket message frame. See
     * `runApiOptionsShape.webSocketMaxPayload` for details.
     */
    webSocketMaxPayload?: number | undefined;
    /**
     * When `true`, the `rest-vir-api` response header (which carries `api.definition.apiName`) is
     * not attached to responses, and it is not exposed via the CORS `Access-Control-Expose-Headers`
     * value. Useful when the server should not advertise that it is a rest-vir host.
     *
     * Note: `findDevServerPort` from `@rest-vir/api` relies on this header to identify which
     * port is hosting the api during dev. Disabling the header breaks that discovery path; pin the
     * dev port explicitly in that case.
     *
     * @default false
     */
    disableRestVirApiNameHeader?: boolean | undefined;
};

/**
 * Attach all handlers for an {@link ApiImplementation} to any existing Fastify server.
 *
 * @category Run Api
 * @category Package : @rest-vir/host
 * @example
 *
 * ```ts
 * import fastify from 'fastify';
 * import {attachApi} from '@rest-vir/host';
 *
 * const server = fastify();
 *
 * await attachApi(server, myApiImplementation, {
 *     externalOrigin: 'http://localhost:3000',
 * });
 *
 * await server.listen({port: 3000});
 * ```
 *
 * @package [`@rest-vir/host`](https://www.npmjs.com/package/@rest-vir/host)
 */
export async function attachApi(
    server: Readonly<FastifyInstance>,
    api: Readonly<ApiImplementation>,
    options: Readonly<ApiServerOptions & HandleRouteOptions>,
): Promise<void> {
    const serverLogger = createServerLogger(api.implementation.serverLogger);

    try {
        const attachId = randomString(32);

        if (!server.hasRequestDecorator('restVirContext')) {
            server.decorateRequest('restVirContext');
        }

        await server.register(compressPlugin, {
            encodings: [
                'br',
                'gzip',
                'deflate',
            ],
            /**
             * Skip compression for small responses where the gzip/br overhead costs more CPU than
             * the bandwidth saving. 1 KiB matches Fastify's documented "good default."
             */
            threshold: 1024,
        });

        /**
         * Auto-register `@fastify/multipart` when any endpoint declares `formDataShape`. Without
         * it, Fastify has no parser for `multipart/form-data` requests and the endpoint would fail
         * before reaching the user's handler. Skip when no formData endpoints exist (avoids the
         * plugin overhead) or when the consumer already registered it (e.g. with custom limits).
         */
        if (apiHasFormDataEndpoint(api) && !server.hasRequestDecorator('file')) {
            await server.register(multipartPlugin);
        }

        if (!server.hasRequestDecorator('ws')) {
            await server.register(fastifyWs, {
                /* node:coverage ignore next 15: edge case handling */
                errorHandler(error, webSocket, request) {
                    serverLogger.error(
                        new RestVirHandlerError(
                            {
                                isEndpoint: false,
                                isWebSocket: true,
                                path: request.originalUrl,
                                apiName: api.definition.apiName,
                            },
                            extractErrorMessage(error),
                            HttpStatus.InternalServerError,
                        ),
                    );
                    webSocket.terminate();
                },
                ...(options.webSocketMaxPayload == undefined
                    ? {}
                    : {
                          options: {
                              maxPayload: options.webSocketMaxPayload,
                          },
                      }),
            });
        }

        const postHook = api.implementation.postRouteHook;

        server.addHook('preValidation', async (request, response) => {
            try {
                const preHandlerResult = await preHandler({
                    request,
                    response,
                    api,
                    server: extractRunningServerInfo(options, server),
                    attachId,
                    serverLogger,
                    disableRestVirApiNameHeader: !!options.disableRestVirApiNameHeader,
                });

                if (preHandlerResult?.statusCode && postHook) {
                    const postHookResult = await runPostRouteHook({
                        attachId,
                        originalBody: preHandlerResult.body,
                        originalStatus: preHandlerResult.statusCode,
                        postHook,
                        request,
                        response,
                        server: extractRunningServerInfo(options, server),
                        api,
                        serverLogger,
                    });

                    if (postHookResult) {
                        return handleHandlerOutput(postHookResult, response);
                    }
                }

                return handleHandlerOutput(preHandlerResult, response);
            } catch (error) {
                /**
                 * `RejectRequestError` is the explicit "reject this request with my status" signal
                 * from a host context creator (or any pre-handler step). Honor its status and body
                 * instead of always collapsing to a 500.
                 */
                if (error instanceof RejectRequestError) {
                    return handleHandlerOutput(
                        {
                            statusCode: error.httpStatus,
                            body: error.responseErrorMessage,
                        },
                        response,
                    );
                }
                serverLogger.error(
                    ensureErrorClass(
                        error,
                        RestVirHandlerError,
                        {
                            isEndpoint: undefined,
                            isWebSocket: undefined,
                            path: request.originalUrl,
                            apiName: api.definition.apiName,
                        },
                        combineErrorMessages('Unexpected error', extractErrorMessage(error)),
                        HttpStatus.InternalServerError,
                    ),
                );
                if (options.throwErrorsForExternalHandling) {
                    throw error;
                    /* node:coverage ignore next 9 */
                } else if (response.sent) {
                    /**
                     * Cannot send another response. Bail out quietly. The error was already logged
                     * above; throwing here would trigger the process-wide `unhandledRejection`
                     * listener for nothing.
                     */
                    return;
                } else {
                    response.statusCode = HttpStatus.InternalServerError;
                    return response.send();
                }
            }
        });

        const allPaths = new Set([
            ...getObjectTypedKeys(api.implementation.webSockets || {}),
            ...getObjectTypedKeys(api.implementation.endpoints || {}),
        ]);

        allPaths.forEach((path) => {
            const webSocketImplementation = api.implementation.webSockets?.[path];
            const endpointImplementation = api.implementation.endpoints?.[path];

            if (endpointImplementation && webSocketImplementation) {
                server.route({
                    method: endpointFastifyMethods,
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpointImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                });
                server.route({
                    method: HttpMethod.Get,
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpointImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                    wsHandler(webSocket, request) {
                        return handleRoute({
                            webSocket,
                            request,
                            response: undefined,
                            route: webSocketImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                });
            } else if (endpointImplementation) {
                server.route({
                    method: [
                        ...endpointFastifyMethods,
                        HttpMethod.Get,
                    ],
                    url: path,
                    handler(request, response) {
                        return handleRoute({
                            webSocket: undefined,
                            request,
                            response,
                            route: endpointImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                });
            } else if (webSocketImplementation) {
                server.route({
                    method: HttpMethod.Get,
                    url: path,
                    handler(request, response) {
                        return response.status(HttpStatus.NotFound).send();
                    },
                    wsHandler(webSocket, request) {
                        return handleRoute({
                            webSocket,
                            request,
                            response: undefined,
                            route: webSocketImplementation,
                            attachId,
                            server: extractRunningServerInfo(options, server),
                            options,
                            postRouteHook: postHook,
                            api,
                            serverLogger,
                        });
                    },
                });
            }
        });

        /* node:coverage ignore next 4: this is just here to cover edge cases. */
    } catch (error) {
        serverLogger.error(ensureError(error));
        throw error;
    }
}

/**
 * Returns `true` if any endpoint method in the api uses `formDataShape()` as its `requestData`,
 * which means we need a multipart body parser registered. Used to decide whether to auto-register
 * `@fastify/multipart` in {@link attachApi}.
 *
 * @category Internal
 */
function apiHasFormDataEndpoint(api: Readonly<ApiImplementation>): boolean {
    for (const endpoint of Object.values(api.definition.endpoints)) {
        for (const method of Object.values(endpoint.requests)) {
            if (isFormDataShape(method.requestData)) {
                return true;
            }
        }
    }
    return false;
}

/**
 * Merge the running Fastify server's port with the given service's origin port (if it has a port).
 *
 * @category Internal
 */
export function extractRunningServerInfo(
    serverOptions: Readonly<ApiServerOptions>,
    fastify: Readonly<
        SelectFrom<
            FastifyInstance,
            {
                server: {
                    address: true;
                };
            }
        >
    >,
): RunningServerInfo {
    const address = fastify.server.address();

    const {port: originalPort} = parseUrl(serverOptions.externalOrigin);

    if (!originalPort || check.isString(address) || !address) {
        return {
            serviceOrigin: serverOptions.externalOrigin,
        };
    } else {
        const {origin} = buildUrl(serverOptions.externalOrigin, {
            port: address.port,
        });

        return {
            serviceOrigin: origin,
        };
    }
}
